# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Delver Engine Android

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build android Debug
      run: ./gradlew android:assembleDebug

    - name: Build android Release
      run: ./gradlew android:assembleRelease

    - name: Bundle Debug Apk
      uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: android/build/outputs/apk/debug/android-debug.apk

    - name: Bundle Release Apk
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: android/build/outputs/apk/release/android-release-unsigned.apk
