# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Delver Engine

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build DungeoneerDesktop
      run: ./gradlew DungeoneerDesktop:dist

    - name: Build DelvEdit
      run: ./gradlew DelvEdit:dist

    - name: Bundle Game Jar
      uses: actions/upload-artifact@v4
      with:
        name: game-jar
        path: DungeoneerDesktop/build/libs/game.jar

    - name: Bundle Editor Jar
      uses: actions/upload-artifact@v4
      with:
        name: editor-jar
        path: DelvEdit/build/libs/editor.jar
