# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Delver Engine

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build desktop
      run: ./gradlew lwjgl3:dist

    - name: Build editor
      run: ./gradlew editor:dist

    - name: Bundle Game Jar
      uses: actions/upload-artifact@v4
      with:
        name: game-jar
        path: lwjgl3/build/libs/game.jar

    - name: Bundle Editor Jar
      uses: actions/upload-artifact@v4
      with:
        name: editor-jar
        path: editor/build/libs/editor.jar
